version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build-and-test:
    docker:
      image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
