version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build-and-test:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
